Repository intuit/judo, pull requests merged in 2019-01, with the labels that each got.

#3 add npm badges
  README.md
Labels: internal, skip-release

#4 Docs/readme logo
  README.md
  assets/logo.svg
Labels: internal

#8 add codecov
  .circleci/config.yml
  README.md
  package.json
Labels: internal, release

#10 removing python dependency in README
  README.md
Labels: documentation, internal

#13 Remove old sections from README.md
  README.md
Labels: documentation

#14 11 - Adds installation manual to setup Judo locally
  README.md
Labels: documentation, patch, release

#16 added png logo
  README.md
  assets/logo.png
Labels: documentation, patch
