Repository intuit/judo, pull requests merged in 2019-10, with the labels that each got.

#32 5 - Adding error handler for invalid YAML
  src/judo.js
  src/judo.test.js
Labels: enhancement, hacktoberfest, minor, release

#33 34: Adding support for JSON files
  README.md
  src/judo.js
  src/judo.test.js
  test-examples/simple-test-suite/hello-world.json
Labels: enhancement, minor, release

#36 #30 Update dependencies to pass security audit
  package-lock.json
  package.json
Labels: patch, release

#37 Update engines according to the documentation
  package.json
Labels: patch, release
